/**
 * Generates scripts/map-voice-cache-keys.sql from canonical Omoi copy + hashes.
 *
 * Usage:
 *   pnpm exec tsx scripts/generate-map-voice-cache-keys-sql.ts
 *
 * Run the output SQL in Cloudflare D1 (Dashboard console or wrangler d1 execute).
 */
import crypto from "crypto";
import fs from "fs";
import path from "path";
import { OMOI_FALLBACK_KNOWLEDGE } from "../src/lib/ai-config";
import { OMOI_VOICE_CACHE_KEYS, OMOI_WELCOME_MESSAGE } from "../src/lib/omoi-voice-cache";

type Mapping = {
  cacheKey: string;
  text: string;
  hash: string;
  skip?: boolean;
};

const DEFAULT_FALLBACK_TEXT =
  'I can help with Nhlanhla\'s background, skills, services, projects, resume, newsletter, contact details, socials, or general site navigation. Try asking something like "What services do you offer?" or "How can I get in touch?"';

function hashText(text: string): string {
  return crypto.createHash("sha256").update(text.trim()).digest("hex");
}

function buildMappings(): Mapping[] {
  const mappings: Mapping[] = [
    {
      cacheKey: OMOI_WELCOME_MESSAGE.cacheKey,
      text: OMOI_WELCOME_MESSAGE.content,
      hash: hashText(OMOI_WELCOME_MESSAGE.content),
      skip: true, // already mapped by user
    },
    ...OMOI_FALLBACK_KNOWLEDGE.map((rule) => ({
      cacheKey: rule.cacheKey,
      text: rule.response,
      hash: hashText(rule.response),
    })),
    {
      cacheKey: OMOI_VOICE_CACHE_KEYS.default,
      text: DEFAULT_FALLBACK_TEXT,
      hash: hashText(DEFAULT_FALLBACK_TEXT),
    },
  ];

  return mappings;
}

function generateSql(mappings: Mapping[]): string {
  const lines: string[] = [
    "-- Map remaining ai_voice_cache rows to stable cache_key values",
    "-- Generated by scripts/generate-map-voice-cache-keys-sql.ts — re-run after copy changes.",
    "-- welcome is skipped (already set). Run each statement in Cloudflare D1 console.",
    "",
    "-- Preview unmapped rows before updating:",
    "SELECT id, response_text_hash, cache_key, substr(response_text, 1, 72) AS preview, substr(audio_url, 1, 96) AS audio_url",
    "FROM ai_voice_cache",
    "WHERE cache_key IS NULL OR cache_key = ''",
    "ORDER BY id;",
    "",
  ];

  for (const entry of mappings) {
    if (entry.skip) {
      lines.push(`-- [skip] ${entry.cacheKey} already mapped`);
      lines.push("");
      continue;
    }

    const preview = entry.text.replace(/\s+/g, " ").slice(0, 72);
    lines.push(`-- ${entry.cacheKey}: ${preview}...`);
    lines.push(`-- hash: ${entry.hash}`);
    lines.push(
      `UPDATE ai_voice_cache SET cache_key = '${entry.cacheKey}' WHERE response_text_hash = '${entry.hash}';`,
    );
    lines.push(
      `UPDATE ai_voice_cache SET cache_key = '${entry.cacheKey}' WHERE cache_key IS NULL AND instr(audio_url, '${entry.hash}') > 0;`,
    );
    lines.push("");
  }

  lines.push("-- Verify:");
  lines.push(
    "SELECT cache_key, response_text_hash, substr(audio_url, 1, 96) AS audio_url FROM ai_voice_cache ORDER BY cache_key;",
  );
  lines.push("");
  lines.push("-- Still unmapped (map manually if you have S3 audio for other copy):");
  lines.push(
    "SELECT id, response_text_hash, substr(response_text, 1, 72) AS preview FROM ai_voice_cache WHERE cache_key IS NULL OR cache_key = '' ORDER BY id;",
  );
  lines.push("");

  return lines.join("\n");
}

function main() {
  const mappings = buildMappings();
  const sql = generateSql(mappings);
  const outPath = path.join(process.cwd(), "scripts", "map-voice-cache-keys.sql");

  fs.writeFileSync(outPath, sql);

  console.log(`Wrote ${outPath}`);
  console.log("\nMappings (excluding welcome):");
  for (const entry of mappings.filter((m) => !m.skip)) {
    console.log(`  ${entry.cacheKey.padEnd(10)} ${entry.hash}`);
  }
}

main();
