-- Map remaining ai_voice_cache rows to stable cache_key values
-- Generated by scripts/generate-map-voice-cache-keys-sql.ts — re-run after copy changes.
-- welcome is skipped (already set). Run each statement in Cloudflare D1 console.

-- Preview unmapped rows before updating:
SELECT id, response_text_hash, cache_key, substr(response_text, 1, 72) AS preview, substr(audio_url, 1, 96) AS audio_url
FROM ai_voice_cache
WHERE cache_key IS NULL OR cache_key = ''
ORDER BY id;

-- [skip] welcome already mapped

-- about: Ah, Nhlanhla Junior Malaza—he’s an accomplished Software Developer, DevO...
-- hash: 37f94b48cf633d48d3eb5558e4d83519d1ffeffa826391f4f4bd9f62ae9bdc61
UPDATE ai_voice_cache SET cache_key = 'about' WHERE response_text_hash = '37f94b48cf633d48d3eb5558e4d83519d1ffeffa826391f4f4bd9f62ae9bdc61';
UPDATE ai_voice_cache SET cache_key = 'about' WHERE cache_key IS NULL AND instr(audio_url, '37f94b48cf633d48d3eb5558e4d83519d1ffeffa826391f4f4bd9f62ae9bdc61') > 0;

-- services: Web dev, mobile, cloud, AI... Nhlanhla does it all. *Munch*... This loll...
-- hash: c2cff6f05c9ab441cc1ce52ecba6142a5ac49064a721540e6bcb528b011b69b1
UPDATE ai_voice_cache SET cache_key = 'services' WHERE response_text_hash = 'c2cff6f05c9ab441cc1ce52ecba6142a5ac49064a721540e6bcb528b011b69b1';
UPDATE ai_voice_cache SET cache_key = 'services' WHERE cache_key IS NULL AND instr(audio_url, 'c2cff6f05c9ab441cc1ce52ecba6142a5ac49064a721540e6bcb528b011b69b1') > 0;

-- skills: Oh no, where do I begin? What if I miss something and it causes confusio...
-- hash: 45002da0e0b7d12351c0e200f9f503fc8c6f1a1bfa8490f2be031065f46cff9c
UPDATE ai_voice_cache SET cache_key = 'skills' WHERE response_text_hash = '45002da0e0b7d12351c0e200f9f503fc8c6f1a1bfa8490f2be031065f46cff9c';
UPDATE ai_voice_cache SET cache_key = 'skills' WHERE cache_key IS NULL AND instr(audio_url, '45002da0e0b7d12351c0e200f9f503fc8c6f1a1bfa8490f2be031065f46cff9c') > 0;

-- projects: Projects? Oh no, what if you don’t like what you see? Or worse, what if ...
-- hash: 2a7ee9be7352a673da7642103fe8d2e6e01d5b3b7b39331c5ff9b6e831b28f11
UPDATE ai_voice_cache SET cache_key = 'projects' WHERE response_text_hash = '2a7ee9be7352a673da7642103fe8d2e6e01d5b3b7b39331c5ff9b6e831b28f11';
UPDATE ai_voice_cache SET cache_key = 'projects' WHERE cache_key IS NULL AND instr(audio_url, '2a7ee9be7352a673da7642103fe8d2e6e01d5b3b7b39331c5ff9b6e831b28f11') > 0;

-- contact: Oh, contacting him is easy, but... what if your message gets lost in cyb...
-- hash: f8a46aa0d60e0ee6d0cb16088e875b61310450915819f171ed56274f2069fd6d
UPDATE ai_voice_cache SET cache_key = 'contact' WHERE response_text_hash = 'f8a46aa0d60e0ee6d0cb16088e875b61310450915819f171ed56274f2069fd6d';
UPDATE ai_voice_cache SET cache_key = 'contact' WHERE cache_key IS NULL AND instr(audio_url, 'f8a46aa0d60e0ee6d0cb16088e875b61310450915819f171ed56274f2069fd6d') > 0;

-- resume: Oh, the resume? Yes, of course! But what if the link doesn’t work or you...
-- hash: c44cc1ca95f56e923fe7f7ab682eeb3ead9a2c04454cf5a3028b8467233ebb44
UPDATE ai_voice_cache SET cache_key = 'resume' WHERE response_text_hash = 'c44cc1ca95f56e923fe7f7ab682eeb3ead9a2c04454cf5a3028b8467233ebb44';
UPDATE ai_voice_cache SET cache_key = 'resume' WHERE cache_key IS NULL AND instr(audio_url, 'c44cc1ca95f56e923fe7f7ab682eeb3ead9a2c04454cf5a3028b8467233ebb44') > 0;

-- greeting: H-Hello. I'm Omoi. I'm helping Nhlanhla, but I can't help but wonder... ...
-- hash: 8246c217bd73fe3dcac55f35042d5be6e7f478b19e1f356d65420077f97e3d0d
UPDATE ai_voice_cache SET cache_key = 'greeting' WHERE response_text_hash = '8246c217bd73fe3dcac55f35042d5be6e7f478b19e1f356d65420077f97e3d0d';
UPDATE ai_voice_cache SET cache_key = 'greeting' WHERE cache_key IS NULL AND instr(audio_url, '8246c217bd73fe3dcac55f35042d5be6e7f478b19e1f356d65420077f97e3d0d') > 0;

-- default: I can help with Nhlanhla's background, skills, services, projects, resum...
-- hash: 4d5e23519dad7a80d04c3e77efba6e89fc6476626b39cb61e88e618f617c9e53
UPDATE ai_voice_cache SET cache_key = 'default' WHERE response_text_hash = '4d5e23519dad7a80d04c3e77efba6e89fc6476626b39cb61e88e618f617c9e53';
UPDATE ai_voice_cache SET cache_key = 'default' WHERE cache_key IS NULL AND instr(audio_url, '4d5e23519dad7a80d04c3e77efba6e89fc6476626b39cb61e88e618f617c9e53') > 0;

-- Verify:
SELECT cache_key, response_text_hash, substr(audio_url, 1, 96) AS audio_url FROM ai_voice_cache ORDER BY cache_key;

-- Still unmapped (map manually if you have S3 audio for other copy):
SELECT id, response_text_hash, substr(response_text, 1, 72) AS preview FROM ai_voice_cache WHERE cache_key IS NULL OR cache_key = '' ORDER BY id;
