# Node.js
# Docs for the Azure Web Apps Deploy action:
# https://github.com/azure/functions-action
# Build a Node.js project with Azure Pipelines.
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Add steps that publish artifacts, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Build and deploy Node.js project to AWS Lightsail server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # set this to the project path, defaults to the repository root
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './'
  # set this to the node version to use (supports 8.x, 10.x, 12.x)
  NODE_VERSION: '16.x'
  AWS_APP_NAME: 'new-site-nextjs'
  # DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  DEPLOY_HOST: 54.90.76.40
  ENV_NAME: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # - name: 'Show me my variables'
      #   shell: bash
      #   run: |
      #     echo "$DEPLOY_HOST"
      #     echo $ENV_NAME
      #     echo $NODE_VERSION
      #     echo $DEPLOY_KEY
      #     echo $AWS_APP_NAME
      #     echo "$DEPLOY_KEY" > ssh-private-key

      #     npm ci
      #     npm run build

      #     chmod 600 ssh-private-key
      #     scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key $GITHUB_WORKSPACE/.next ubuntu@54.144.211.235:/var/www/54.144.211.235/.next

      # - name: 'Build Next.js app'
      #  shell: bash
      #  run: |
      #    npm install
      #    npm run build

      # - name: 'Deploy to AWS server'
      #  shell: bash
      #  run: |
      #    scp -o StrictHostKeyChecking=no -r -i $PUBLIC_KEY $GITHUB_WORKSPACE/.next ubuntu@$DEPLOY_HOST:/var/www/54.90.76.40/.next
      #    echo "Finished and done!"
